name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: main

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Se connecter au VPS et lancer Docker Compose
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}  # IP ou domaine de ton VPS
          username: ${{ secrets.VPS_USER }}  # Nom d'utilisateur SSH
          key: ${{ secrets.VPS_SSH_KEY }}  # Clé privée SSH
          script: |
            cd /home/debian/projects/Secret-Manager-Frontend  # Remplace par le chemin correct sur ton VPS
            git pull origin main  # Mettre à jour le code
            docker compose down  # Arrêter les conteneurs existants
            docker compose up -d --build --remove-orphans  # Redémarrer avec les dernières modifications
